### ISSUE TITLE
Line's background color

### ISSUE THREAD

**Issue by muhanerd** [icsharpcode/AvalonEdit#102]
how could I change the background color of a specific line? I am trying to build a diff tool. I have a model with lines. Each line has a property indicating whether it's inserted, deleted, modified... I would like to change the background color of those lines according to their state.

**Comment by jimfoye** [comment]
Implement IBackgroundRenderer and add to the TextView.BackgroundRenderers collection.

**Comment by muhanerd** [comment]
Thank you for the hint! I put her my implementation (in case someone is interested).

`    public class HighlightCurrentLineBackgroundRenderer : IBackgroundRenderer
    {
        private TextEditor _editor;
        public List<DiffPiece> Lines { get; set; } // DiffPlex diff-model's lines

        public HighlightCurrentLineBackgroundRenderer(TextEditor editor)
        {
            _editor = editor;
        }

        public KnownLayer Layer
        {
            get { return KnownLayer.Selection; }
        }

        public void Draw(TextView textView, DrawingContext drawingContext)
        {
            if (_editor.Document == null)
                return;

            textView.EnsureVisualLines();

            for (var i=0; i<Lines.Count;i++)
            {
                var diffLine = Lines[i];
                if (!string.IsNullOrEmpty(diffLine.Text))
                {
                    var highlight = GetLineBackgroundBrush(diffLine);
                    var currentLine = _editor.Document.GetLineByNumber(i+1);
                    foreach (var rect in BackgroundGeometryBuilder.GetRectsForSegment(textView, currentLine))
                    {
                        drawingContext.DrawRectangle(highlight, null, new Rect(rect.Location, new Size(rect.Width, rect.Height)));
                    }
                }
            }
        }

        private Brush GetLineBackgroundBrush(DiffPiece line)
        {
            var highlight = Brushes.Transparent;
            switch (line.Type)
            {
                case ChangeType.Inserted:
                    highlight = Brushes.Green;
                    break;
                case ChangeType.Deleted:
                    highlight = Brushes.Red;
                    break;
                case ChangeType.Modified:
                    highlight = Brushes.Yellow;
                    break;
            }

            return highlight;
        }
    }`

And I call it like this:

        private void BuildDiffPane(TextEditor textEditor, DiffPaneModel model)
        {
            var backgroundRenderer = new HighlightCurrentLineBackgroundRenderer(textEditor);
            textEditor.TextArea.TextView.BackgroundRenderers.Add(backgroundRenderer);
            backgroundRenderer.Lines = model.Lines;

            foreach (var diffLine in model.Lines)
            {                
                if (!string.IsNullOrEmpty(diffLine.Text))
                {
                    textEditor.AppendText(diffLine.Text);
                }
                
                textEditor.AppendText(Environment.NewLine);
            }

            textEditor.TextArea.TextView.InvalidateLayer(KnownLayer.Selection);
        }

**Comment by Dirkster99** [comment]
Here is a [diff tool](https://github.com/Dirkster99/Aehnlich) that does it in action (screenshots may not be up-to-date sorry) ...

**Comment by siegfriedpammer** [comment]
This should be what you are looking for: https://github.com/siegfriedpammer/AvalonEditSamples/tree/master/TextMarkerSample
