### ISSUE TITLE
Button images for the search panel are not displayed

### ISSUE THREAD

**Issue by Eferus** [icsharpcode/AvalonEdit#117]
The images associated to the buttons do not appear in the search panel.
![image](https://cloud.githubusercontent.com/assets/11998540/24758701/6e80be8e-1ae3-11e7-8d4f-337c35a270dd.png)

I use the version 5.0.3.0. 
I uninstalled and reinstalled the package and nothing changed.

Edit: To fix the problem I override the style of the search panel. I added the following snippet and I replaced the images of the buttons by my own images. 
```   
<ControlTemplate.Resources>
        <Style TargetType="{x:Type Button}" BasedOn="{StaticResource {x:Type Button}}"/>
</ControlTemplate.Resources>
```

**Comment by jogibear9988** [comment]
I think it's not a problem with AvalonEdit Library. Maybe you have overwritten default Style of Button?
