### ISSUE TITLE
MoveFocus not working

### ISSUE THREAD

**Issue by avitiw** [icsharpcode/AvalonEdit#118]
I am using AvalonEdit as custom control. I wan to move focus to previous or next element.
In the class derived from TextEditor following happens:

TextArea.MoveFocus(new TraversalRequest(FocusNavigationDirection.Next)) 
works. But

TextArea.MoveFocus(new TraversalRequest(FocusNavigationDirection.Previous)) 
does not works.

**Comment by mrlacey** [comment]
@avitiw (and anyone else who finds their way here) I had a similar issue and addressed it with the following. Because the `TextArea` is inside the `TextEditor` and both are focusable, it's necessary to allow for both, depending on the direction of navigation.

```cs
private void OnPreviewKeyDown(object sender, System.Windows.Input.KeyEventArgs e)
{
    if (e.Key == Key.Tab)
    {
        var shiftPressed = (e.KeyboardDevice.Modifiers & ModifierKeys.Shift) == ModifierKeys.Shift;

        if (shiftPressed)
        {
            (sender as TextEditor).MoveFocus(new TraversalRequest(FocusNavigationDirection.Previous));
        }
        else
        {
            (sender as TextEditor).TextArea.MoveFocus(new TraversalRequest(FocusNavigationDirection.Next));
        }

        e.Handled = true;
    }
}
```
