### ISSUE TITLE
Mix mode tabs and spaces

### ISSUE THREAD

**Issue by Asser82** [icsharpcode/AvalonEdit#121]
Hi,
I have found something strange here. When I set the editor to use spaces for tabs and afterwards paste in code from an external editor where tabs are used, the calculation of spaces to insert when tab is pressed seems to be wrong. The problem seems to be, that the inserted tabs are counted as characters. Here is an example:

1) Set the editor to use 4 spaces for tabs, set the whitespaces to be displayed
2) Go to Notepad++ or similar, ensure that tabs are used instead of spaces, create these two lines:

a(tab)aa
aa(tab)(tab)a

3) Copy them back to the avalon editor
4) Go to the end of each line, and try to get the line ends on the same imaginary tab raster by pressing tab only

This is not possible. Compare the use case to the Notepad++ handling.

**Comment by jimfoye** [comment]
I did steps 1-3 and everything looked correct, the editor expanded each tab to four spaces.

What do you mean by "try to get the line ends on the same imaginary tab raster by pressing tab only"?

**Comment by Asser82** [comment]
OK, I wanted to demonstrate the problem by working with the displayed column the caret is curently on, but even this is not correct. I have installed SharpDevelop 5.1 to have no influence from our code. Then I entered:

a (tab) aa (tab) (tab) b

Tabs are real tabs, no spaces. If the caret is behind the b, SD displays me Column 17. If I now press return and fill the next line with some character, so that the caret is again behind the b, SD displays Column 14, which I have also expected for the first line.

**Comment by siegfriedpammer** [comment]
I finally understand the problem:

> OK, I wanted to demonstrate the problem by working with the displayed column the caret is curently on, but even this is not correct. I have installed SharpDevelop 5.1 to have no influence from our code.

AvalonEdit by itself does not calculate something like a "column". Even the "visual column" concept is not what you are looking for. The visual length of a tab character in AvalonEdit is always 2 (it consists of a "tab" glyph character and a space). The visual length of a space is always 1.

But, the column calculation you are referring to has to take the width of a tab character into account, which is customizable. As an example you provide SharpDevelop. If we take a look at how SharpDevelop calculates the line, column and offset numbers in the status bar, we have the following code:

https://github.com/icsharpcode/SharpDevelop/blob/8a1a71cc801b4bed1668a72638d244ba47637434/src/AddIns/DisplayBindings/AvalonEdit.AddIn/Src/CodeEditor.cs#L389-L399

```csharp
389	var document = this.Document;
390	int lineOffset = document.GetLineByNumber(this.Line).Offset;
391	int chOffset = this.Column;
392	int col = 1;
393	for (int i = 1; i < chOffset; i++) {
394		if (document.GetCharAt(lineOffset + i - 1) == '\t')
395			col += CodeEditorOptions.Instance.IndentationSize;
396		else
397			col += 1;
398	}
399	SD.StatusBar.SetCaretPosition(col, this.Line, chOffset);
```

The line and offset numbers are taken straight from AvalonEdit's caret position. The column is calculated by counting each character as 1 except for tabs, which are counted as 4 (or any other number you configure). So an input like "(space)(space)(tab)" is visually on column 4, However SharpDevelop calculates 1 + 1 + tabSize (which is 1 + 1 + 4 = 6).

You are free to create your own way of calculating the (visual) column. As the code above is not part of AvalonEdit and the "bug" is somewhere else, I am going to close this issue.
