### ISSUE TITLE
DarkTheme / Customize Highlighting (XSHD)

### ISSUE THREAD

**Issue by Kabennsky** [icsharpcode/AvalonEdit#128]
I am trying use AvalonEdit in my Application for XML Transformations. I always prefer the DarkTheme options in Editors like VisualStudio, AndroidStudio, NetBeans and so on..

I didn't find a solution for the AvalonEdit, so I decided to edit the current Editor with it Highlighting. Background was easy and with editing the XSHD-Files changing Highlighting seemed easy to.
But I am not able to change to color for web links like http://www.w3.org/1999/XSL/Transform in xmlns:xsl="http://www.w3.org/1999/XSL/Transform". 

The only way I found was to set the enableHyperlinks = false in the TextEditorOptions class.
Is there a way to set this in xaml or xshd?

**Comment by dgrunwald** [comment]
You'll want to set `textEditor.TextArea.TextView.LinkTextForegroundBrush`.

**Comment by Kabennsky** [comment]
Thank you very much. It works! :)
