### ISSUE TITLE
Color background in XSHD

### ISSUE THREAD

**Issue by zaksmolen** [icsharpcode/AvalonEdit#142]
There are foreground and background properties on color tags in XSHD, but the background isn't used for anything. I have seen examples of background highlighting by implementing an IBackgroundRenderer, but that usually finds the highlighting by some custom searching or matching. Is there any way to just blanket render all the backgrounds defined in your syntax highlighting? I was toying with the idea of getting all of the matches and making an IBackgroundRenderer that then colors them, but that's complicated by the fact that syntax highlighting only keeps track of part of the document at a time.

Any advice on this would be appreciated. I know I could always probably recreate the matching conditions I define in the syntax highligting, but that would mean a lot more file parsing (and we have some massive files) and redundant parsing, when what I want is exactly there already.

**Comment by siegfriedpammer** [comment]
I just tested this. Setting the `background` property on `Color` or `Keywords` elements is working just fine. This was implemented in fc54a4e6eed67224536a966bc588829c18a16e40 over 7 years ago.
