### ISSUE TITLE
Right Click Event

### ISSUE THREAD

**Issue by Igie** [icsharpcode/AvalonEdit#147]
Hello, first of all, thank you for creating such amazing text editor

Secondly, I came to an issue of executing code based on selected text/caret position.
To compare, WPF standard Paragraphs have Inlines, and I can execute/create Context menu based on Inline selected (extending Run class with command and custom Object). However, I fail to understand how I could achieve that in AvalonEdit. Please, enlighten me.

**Comment by siegfriedpammer** [comment]
See https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/TextView/DecompilerTextView.cs#L190 and https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/ContextMenuEntry.cs#L162
