### ISSUE TITLE
Cannot use binding?

### ISSUE THREAD

**Issue by mysteryx93** [icsharpcode/AvalonEdit#150]
I just found out about AvalonEdit which sounds very promising. However, I cannot apply any binding to it! I'm trying to bind to the Text property. Bindings can only be applied to Dependency Properties, and properties have not been implemented as Dependency Properties! That really is a huge limitation. It means this cannot be used within a MVVM code design.

Or am I missing something?

**Comment by dgrunwald** [comment]
See #84 for an explanation why this is not possible.
