### ISSUE TITLE
European characters

### ISSUE THREAD

**Issue by starzen** [icsharpcode/AvalonEdit#152]
When loading a file with european characters (in this case swedish) the characters do not show properly. Using default encoding.

**Comment by goswinr** [comment]
Did you try changing the Font Family?

**Comment by starzen** [comment]
any idea what to change it to?

in Notepad ++ if i set the Northern European -> OEM 861 it displays properly

i think that is the codepage. I am using Consolas which i think has that OEM 861 but i have no idea how to set that in avalonedit

any help greatly appreciated

**Comment by dgrunwald** [comment]
AvalonEdit internally uses `char[]`, and thus always UTF-16.
How are you loading the file? You're almost certainly using the wrong encoding when opening the file.

**Comment by starzen** [comment]
originally i had a similar issue with latin characters. Found it i was loading as UTF-8 so i changed it to default encoding (FileReader.OpenStream). That fixed the issue with the latin characters

But now i ran into the problem with the swedish ones

even in Notepad++ after loading the file it shows incorrectly until i change the character set to 850/861/etc

I have tested the same text file in SharpDevelop with the same result

**Comment by starzen** [comment]
i think i figured this out. The file in question was created in OEM encoding

i did not have an option for that so after adding the OEM encoding option it is able to display the file properly

thanks for all the help
