### ISSUE TITLE
Possible to use as Hex Editor textbox?

### ISSUE THREAD

**Issue by ajhalls** [icsharpcode/AvalonEdit#157]
I love the idea of using this for syntax highlighting and so on, but I am curious if there is any way to adjust the lines so that it shows the Hex values of binary files?

Here is what I had in mind from another file viewer called V64:
![capture](https://user-images.githubusercontent.com/5520815/48390916-758c3680-e6c1-11e8-973c-25f3f3fa3199.PNG)

So you would have a line that was the actual text, and then a line with the first 4 bits in hex, and then the next line with the 4 bits in hex to get the full byte.

While I could alter the incoming file to show it that way in just a regular text box, I would rather use AvalonEdit so I could use highlighting and more ideal color schemes than would be possible with a textbox.

**Comment by Dirkster99** [comment]
I think you should use an [HexEditor](https://github.com/abbaye/WpfHexEditorControl) control to view that type of content.
