### ISSUE TITLE
Is this still under maintenance ?

### ISSUE THREAD

**Issue by baoduy** [icsharpcode/AvalonEdit#159]
This is interesting project, but not sure it is still under maintenance?

**Comment by goswinr** [comment]
It works great. Try it ! I am very happy with it.

**Comment by baoduy** [comment]
@goswinr ,
Thanks, I'm start using it now. meanwhile, I'm happy with the way to define the custom highlighting schema.

**Comment by baoduy** [comment]
There is a few useful full request sine 2015 still open now. Shall I clone and maintain a separate version?

**Comment by jogibear9988** [comment]
what pull req. do you need to be merged?

**Comment by baoduy** [comment]
Hi @jogibear9988
I’m interesting on the PR #75.
Thanks for your help.

**Comment by jogibear9988** [comment]
I'll look at the pull reqs. next week.

**Comment by baoduy** [comment]
Thank you so much.

**Comment by jogibear9988** [comment]
if've added a new pull req for this #170 

so the project is on maintenance, this issue can be closed
