### ISSUE TITLE
Port it to WPF .net Core 3.0 

### ISSUE THREAD

**Issue by geotinc** [icsharpcode/AvalonEdit#162]
Hey,

Any plan to port the lib to WPF .net core 3.0 ?

Thanks for reply

**Comment by christophwille** [comment]
We haven't looked into that (and how much work that might be)

**Comment by jogibear9988** [comment]
see #168

**Comment by superlloyd** [comment]
Probably no longer relevant, but I just forked it and compiled it for .NET Core and successfully ran the sample app!
https://github.com/superlloyd/AvalonEdit
