### ISSUE TITLE
AvalonEdit Nuget Package Version Mismatch

### ISSUE THREAD

**Issue by chrpai** [icsharpcode/AvalonEdit#165]
I just used Nuget to install AvalonEdit 5.0.4.  However when I look at the file packages\AvalonEdit.5.0.4\libn\Net40\ICSharpCode.AvalonEdit.dll  the file properties says that it's version 5.0.3.

**Comment by chrpai** [comment]
The DLL in the Net35 folder says that it's 5.0.3.0 also.     I'm wondering if it was just compiled with the wrong version or if the Nuget package has old / wrong files in it.

**Comment by jogibear9988** [comment]
hopefully i'll fix that in #168 too

**Comment by jogibear9988** [comment]
should be fixed in new nugets
