### ISSUE TITLE
Provide proper license details (copyright holder)

### ISSUE THREAD

**Issue by ygoe** [icsharpcode/AvalonEdit#166]
I know now, after reading your NuGet page, GitHub page and website, that this code is licensed under the terms of the [MIT license](https://opensource.org/licenses/MIT).

But that linked text isn't a proper license, it's just a template. The license would need to contain a copyright holder. I'm about to use this library in a client's project which requires me to provide a proper license attribution. If you'd like me to call you "&lt;COPYRIGHT HOLDER&gt;", please confirm, because that looks like a strange name for a developer. But I'm happy to note that name in my license documentation if that's the case.

**Comment by dgrunwald** [comment]
Looks like [license.txt](https://github.com/icsharpcode/SharpDevelop/blob/master/doc/license.txt)/[copyright.txt](https://github.com/icsharpcode/SharpDevelop/blob/master/doc/copyright.txt) never made it into this repository (AvalonEdit was originally part of the SharpDevelop repository).

The license text is also at the beginning of each source file.

**Comment by jogibear9988** [comment]
@dgrunwald is avalonedit not MIT licenced?

**Comment by christophwille** [comment]
The license *is* MIT.

**Comment by christophwille** [comment]
I have added the LICENSE file explicitly with commit https://github.com/icsharpcode/AvalonEdit/commit/bc6ff4cd601a466acc2200e4ebb979c1b958a867.
