### ISSUE TITLE
Remove Code in #if NREFACTORY

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/AvalonEdit#174]
Ties back to pull request https://github.com/icsharpcode/AvalonEdit/pull/168

Anything inside #if NREFACTORY is no longer needed. ToDo after PR has been merged (to not add anything more to the PR commits)

**Comment by dgrunwald** [comment]
There's also left-over `#if DOTNET4`/`#else` constructs from the .NET 3.5 compatibility.
