### ISSUE TITLE
Bug dragging selection and dropping into itself.

### ISSUE THREAD

**Issue by bdachev** [icsharpcode/AvalonEdit#178]
One can select multiple lines and drag them in the position within the selection. That leads weird effects. In general such action this must be disabled and there is a corresponding code for this in SelectionMouseHandler.cs:

`void textArea_Drop(object sender, DragEventArgs e)`

but it does not execute because of a bug in

```
void StartDrag()
		{
			// prevent nested StartDrag calls
			mode = MouseSelectionMode.Drag;
			
			// mouse capture and Drag'n'Drop doesn't mix
			textArea.ReleaseMouseCapture();
```

where

`textArea.ReleaseMouseCapture();
`

resets the mode to 'None'

**Comment by jogibear9988** [comment]
could you create a pull req?

**Comment by bdachev** [comment]
Hi Jochen, 
Adding one more `mode = MouseSelectionMode.Drag;` right after `textArea.ReleaseMouseCapture();` seems to fix the problem for our project. But there might be more adequate solution and that is why we decided to post the issue here. If you think it is correct fix I will be happy to make a pull request for you.
B.

**Comment by jimfoye** [comment]
Swapping the calls works for me.
