### ISSUE TITLE
Extended Highlighting Manager

### ISSUE THREAD

**Issue by Dirkster99** [icsharpcode/AvalonEdit#179]
Hi Guys,

I am done with the [ThemeableHighlightingManager](https://github.com/Dirkster99/AvalonEditHighlightingThemes). I have integrated it here: [Dirkster99/Aehnlich](https://github.com/Dirkster99/Aehnlich) and it works pretty good :-)

So, I am wondering if anyone is interested in integrating this into a later version of AvalonEdit itself.

Even if not, should there not at least a reviewed list of known AvalonEdit extensions and sample projects (?) so people have an easier time finding these things(?):
- [dirkster99/AvalonEditHighlightingThemes](https://github.com/Dirkster99/AvalonEditHighlightingThemes)
- [siegfriedpammer/AvalonEditSamples](https://github.com/siegfriedpammer/AvalonEditSamples)
- 

I hope I find the time to write another CodeProject article about the HighlightingManager extension but apart from that I really think this is the coolest WPF open source text editor there is. Thanks a lot for your work :-)

**Comment by jogibear9988** [comment]
i've added it to the readme

**Comment by christophwille** [comment]
How about an extensions & separate articles wiki article? We have something along the lines in ILSpy https://github.com/icsharpcode/ILSpy/wiki/Plugins - the Wiki has the added advantage of "editable by everyone"

**Comment by jogibear9988** [comment]
i look to move it
