### ISSUE TITLE
[Question] Highlight matching brackets in AvalonEdit

### ISSUE THREAD

**Issue by PeskovV** [icsharpcode/AvalonEdit#180]
I want to clarify one moment:

Is there built-in tools in AvalonEdit for highlight matching brackets (or another characters)? For example:
![Screenshot_1](https://user-images.githubusercontent.com/26106827/60587657-ae3a6680-9d9d-11e9-93d5-6f8f695dcc8b.png)

**Comment by wanglong126** [comment]
Have you implemented this method

**Comment by PeskovV** [comment]
@wanglong126 Yes, but my answer only on russian (link to stackoverflow): https://bit.ly/2S02yzF

**Comment by wanglong126** [comment]
I have just seen such articles this morning, and I am ready to learn more about them. Thank you for your reply and wish you all the best
