### ISSUE TITLE
More sample projects

### ISSUE THREAD

**Issue by Dirkster99** [icsharpcode/AvalonEdit#185]
I have added another sample project to the [Wiki page](https://github.com/icsharpcode/AvalonEdit/wiki/Samples-and-Articles) and slightly changed the layout (hope thats OK).

Another sample application to list in the Readme.md would be:
- SharpDevelop
- [Aehnlich](https://github.com/Dirkster99/Aehnlich)

**Comment by christophwille** [comment]
SharpDevelop is long out of development, and it was using a different build of AvalonEdit (it had preprocessor directives that we just recently removed from the AE codebase)

**Comment by Dirkster99** [comment]
Oh, OK, maybe its useful to state it at the SharpDevelop site or archive the project so others know as well?
I could not find any statement about the discontinuation, I used to use SharpDevelop to learn API usages for AvalonEdit :-( Maybe ist still useful to state that AvalonEdit was used in SharpDevelop up to version xyz - this could still be useful since the AvalonEdit API has been quit stable during the last 5 or so years ...

Anyways, For the Ähnlich app it would be cool if its listed as an AvalonEdit example as it sports a lot of AvalonEdit's current features plus Background rendering computed in a background task etc... something like:

[Ähnlich](https://github.com/Dirkster99/Aehnlich)
Shows differences on directories, their content, and differences in a text file

would be a helpful text I think ...

**Comment by dgrunwald** [comment]
The preprocessor stuff mostly just meant that some types were in a different assembly+namespace, but the API really hasn't changed much from the version used in SharpDevelop.
I think it can still be a useful example (although quite complex as it often extends AvalonEdit somewhat indirectly through the SharpDevelop addin system).
