### ISSUE TITLE
Support for regular expression highlighting

### ISSUE THREAD

**Issue by carlos357** [icsharpcode/AvalonEdit#186]
I think that it would be nice to support Regular Expression syntax highlighting.

I already have created my own XSHD file for this and It works but it can be improved. If this feature is approved (may be reg exps are not popular enough) I can submit that file.

**Comment by jogibear9988** [comment]
If you'd like to share, create a pull request. ;-)

**Comment by mterwoord** [comment]
@carlos357 Please share the xshd file, as I personally could use it as well. Even if not 100% ideal, it may be a good start (and fit my needs). :-)

**Comment by carlos357** [comment]
Sure. Here it is :-)

      <SyntaxDefinition name="RegExp" extensions=".regexp" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
        <Color name="EscapedCharacters" foreground="Red" />
        <Color name="Delimiters" foreground="Blue" />
        <Color name="Quantifiers" foreground="Green" />
        <Color name="Anchors" foreground="Yellow" />
        <Color name="GroupName" foreground="Violet" />
        <RuleSet>
          <Rule color="GroupName">\?'[^']+'</Rule>
          <Keywords color="Anchors">
            <Word>^</Word>
            <Word>$</Word>
            <Word>\b</Word>
            <Word>\B</Word>
            <Word>\A</Word>
            <Word>\Z</Word>
            <Word>\G</Word>
          </Keywords>
          <Rule color="EscapedCharacters">\\\d\d\d</Rule>
          <Rule color="EscapedCharacters">\\x..</Rule>
          <Rule color="EscapedCharacters">\\c.</Rule>
          <Rule color="EscapedCharacters">\\.</Rule>
          <Keywords color="Delimiters">
            <Word>(</Word>
            <Word>)</Word>
            <Word>[</Word>
            <Word>]</Word>
            <Word>}</Word>
            <Word>{</Word>
          </Keywords>
          <Rule color="Quantifiers">\{\d+,\d+\}\??</Rule>
          <Rule color="Quantifiers">\{,\d+\}\??</Rule>
          <Rule color="Quantifiers">\{\d+,}\??</Rule>
          <Rule color="Quantifiers">\{\d+}\??</Rule>
          <Keywords color="Quantifiers">
            <Word>+</Word>
            <Word>*</Word>
            <Word>?</Word>
            <Word>*?</Word>
            <Word>??</Word>
            <Word>+?</Word>
            <Word>*?</Word>
            <Word>?+</Word>
            <Word>*+</Word>
            <Word>++</Word>
          </Keywords>
        </RuleSet>
      </SyntaxDefinition>

**Comment by mterwoord** [comment]
Awesome. Thanks for posting!
