### ISSUE TITLE
NullReferenceException when binding to TextEditor.Options

### ISSUE THREAD

**Issue by noctis0430** [icsharpcode/AvalonEdit#187]
Encounter the exception during loading UI when trying to bind to ```TextEditor.Options```

```c#
public class MainVM : PropertyChangedBase
{
    // Fields.
    private TextEditorOptions m_Options = new TextEditorOptions();
    // Binding Properties.
    public TextEditorOptions Options 
    {
        get => m_Options;
        set => Set(ref m_Options, value);
    }
}
```

```xml
<avalonEdit:TextEditor Options="{Binding Options}"/>
```

Repro can be found here: [TextEditor.BasicDemo.zip](https://github.com/icsharpcode/AvalonEdit/files/3470893/TextEditor.BasicDemo.zip)

Using AvalonEdit 5.0.4.

**Comment by Dirkster99** [comment]
Hi I stumbled into this one before as well, most of the time you just have to make sure that the TextEditorOptions object is created when your viewmodel is bound. In other times, where this is not enough, you can defines [FallbackValue](https://github.com/Dirkster99/AvalonEdit-Samples/blob/9c4ba7a1671f640c30a30f2c7e9d1f7a72c76a51/source/30_CursorPosition_Edit_Status/Apps/AEDemo/MainWindow.xaml#L173):

```XAML
<Grid.Resources>
    <!-- This resource is necessary to make sure that AvalonEdit always has valid options
         (even when there is no document if options bound to the editor control) -->
    <avalonEdit:TextEditorOptions x:Key="TextEditOptions"/>
  </Grid.Resources>
   <Grid xmlns:avEditEx="clr-namespace:TextEditLib;assembly=TextEditLib">
      <avEditEx:TextEdit
            Name="avEdit"
            DataContext="{Binding DocumentRoot}"
            Options="{Binding TextOptions, FallbackValue={StaticResource TextEditOptions}}"
            Document="{Binding Document, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}"
       />
   </Grid>
```

 to make sure that AvalonEdit has a valid object at all times.

**Comment by noctis0430** [comment]
@Dirkster99 , the fallback value works. Didn't aware that `Binding` allow one to set the fallback value, learnt something new today! Thanks for your help.

**Comment by Dirkster99** [comment]
No problem, I've been using AvalonEdit for years so I thought I'll give something back by providing some simple guides for anyone who wants to learn about its application. Let me know if you have questions about any of my 'AvalonEdit*' sample repositories linked in [AvalonEdit's Wiki page](https://github.com/icsharpcode/AvalonEdit/wiki/Samples-and-Articles) page...
