### ISSUE TITLE
How can I get some extra scrollspace at the bottom of the editor

### ISSUE THREAD

**Issue by danwalmsley** [icsharpcode/AvalonEdit#19]
Currently users can just scroll to the bottom of the file, but I want to scoll further, so the last line of the document can be shown at the top of the editor?

Is this possible?

**Comment by mike-ward** [comment]
Just noticed that `textEditor.Options.AllowScrollBelowDocument` is not working in 5.0.3. I can no longer scroll below the end of the document using the mouse wheel.
