### ISSUE TITLE
Hyperlinks do not work in .NET Core 3.0

### ISSUE THREAD

**Issue by JaykeBird** [icsharpcode/AvalonEdit#191]
Currently testing out AvalonEdit for a WPF app I'm making on .NET Core 3.0. The files I'm opening have links to a website, which AvalonEdit does properly display as hyperlinks. However, Ctrl+clicking on them does nothing. This also extends to email hyperlinks.

To reproduce, build the sample app included with the project here, and open both a .NET 4.5 and .NET Core 3.0 instance of the sample app. Replace the text in both with "https://google.com", and then try Ctrl+clicking on the link that's created.

In .NET Core 3.0, the standard `Process.Start("<url>")` that I had used constantly on .NET Framework doesn't work to open URLs. I dunno if you're using that, but I figured I'd also mention that. :)

**Comment by jogibear9988** [comment]
The issue is described here: https://github.com/dotnet/corefx/issues/33714
