### ISSUE TITLE
Add a method to programmatically insert a new line?

### ISSUE THREAD

**Issue by Nickelony** [icsharpcode/AvalonEdit#193]
Hello!

I recently started using AvalonEdit and I really like the features it provides, but I noticed that there's no method to programmatically insert a new line (for example underneath the caret position).

I tried to add **Enviroment.NewLine** at the end of the caret line, but no success, so I guess it's simply not possible? I haven't found any method that seems to do that.

Regards,
- Nickelony

**Comment by siegfriedpammer** [comment]
If you want to insert a new line **at** the caret position, you can use `TextArea.PerformTextInput("\n")`.
