### ISSUE TITLE
Question: How to set syntax highlighting rules programmatically on the fly

### ISSUE THREAD

**Issue by dbCF** [icsharpcode/AvalonEdit#212]
I am able to set some syntax highlighting rules with `textEditor.SyntaxHighlighting.MainRuleSet.Rules.Add()` Unfortunately, changes to this list are not applied to the editor on the fly and I haven't found any method to trigger a refresh once the editor is loaded.

I intended to use AvalonEdit to highlight multiple user defined values in log files. Is this possible?

Best regards,
   Carsten

**Comment by blakepell** [comment]
I'm currently writing / using AvalonEdit to render text that's colored with ANSI control sequences (think of an SSH window coloring text, that's exactly it).  For this I used a DocumentColorizingTransformer which fires for lines rendered to the screen (and the you do the color stuff in code).  As an example, I could add more ANSI control sequences on the fly if I wanted to (I already know them all but the variables for the rule could come from a database, a file, user input, etc).

**Comment by dbCF** [comment]
I gave it a quick shot and it looks really promising. Thanks a bunch!

**Comment by dbCF** [comment]
The only problem left is: Any change to refresh the currently visible text? If the user changes the filters, they are applied once you've scrolled the text out of view. Would be nice to avoid it.

**Comment by blakepell** [comment]
Oh I see, like it doesn't apply the new filter until text has changed or it's been scrolled?  That one I'm not sure about but I'll think on it (I'm learning AvalonEdit myself).  Some of the documentation I've read says it only applies on demand.  If there's no way to refresh it (that would be a nice feature) then I wonder if a sub optimal hack like inserting and removing a character would trigger it (there is a TextHidden element that might be useful in that case).  Like I said, it feels hacky but might work in a pinch.

**Comment by goswinr** [comment]
@blakepell is your ANSI control sequences parser with Avalonedit  published on Github?

**Comment by blakepell** [comment]
It is, link below. I'll make a few disclaimers.  I'm only handling 24'ish colors and underline/reverse (most multi-user dimension games only support those colors).  A little hacky but I strip the rest of the codes out I don't support before it gets to the terminal.  Also, the `DocumentColorizingTransformer` provides you a line to colorize so to make things easier on myself I provided everything I need to format that line in the line (if a color was started on line 24, when 25 comes down from the server I include the last color from the previous line at the start of line 25), that way, no matter what line or what order AvalonEdit gives me lines in I can color/style it correctly.

Although on reviewing this code just now I see a bug where if I have a style (underline) and a color it only brings the last ANSI code over to the next line.  I'll need to fix that.

Here's the link, the AvalonTerminal folder has most of the pieces in it including the `AnsiColorizer`.  I welcome any feedback.

Repo: https://github.com/blakepell/AvalonMudClient
Folder: https://github.com/blakepell/AvalonMudClient/tree/master/src/Avalon.Client/Controls/AvalonTerminal

**Comment by blakepell** [comment]
Also, for posterity, here is a link to code for a `VisualLineElementGenerator` that will hide most ANSI control sequences in AvalonEdit.

[https://github.com/icsharpcode/AvalonEdit/issues/213#issuecomment-736751158](url)
