### ISSUE TITLE
How to add JSON in converter

### ISSUE THREAD

**Issue by CreateLab** [icsharpcode/AvalonEdit#219]
I try to do like this
but it does not help
```cs
public class HighlightingDefinitionConverter: IValueConverter
    {
        private static readonly HighlightingDefinitionTypeConverter Converter = new HighlightingDefinitionTypeConverter();

        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var json = value as string;
            if (json.Equals("JSON"))
            {
                var xmlTextReader = new XmlTextReader("JSONHighLight.xshd");
                return Converter.ConvertFrom(xmlTextReader);
            }

            return Converter.ConvertFrom(value);
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return Converter.ConvertToString(value);
        }
    }
```

**Comment by siegfriedpammer** [comment]
Could you explain what you want to do?
How would you be using this converter with AvalonEdit?

**Comment by CreateLab** [comment]
> Could you explain what you want to do?
> How would you be using this converter with AvalonEdit?
I bind converter lang to combobox  for choosing highlight
and use converter  switch highliting
https://stackoverflow.com/questions/60324160/avalonedit-how-to-add-new-syntax-in-converter

**Comment by siegfriedpammer** [comment]
Did you take a look at the AvalonEdit sample application?

The dropdown is defined here:
https://github.com/icsharpcode/AvalonEdit/blob/a5691facdde5d06c3de50118c9894970d709ea55/ICSharpCode.AvalonEdit.Sample/Window1.xaml#L74-L77

You can add custom highlighting definitions as follows:
https://github.com/icsharpcode/AvalonEdit/blob/a5691facdde5d06c3de50118c9894970d709ea55/ICSharpCode.AvalonEdit.Sample/Window1.xaml.cs#L44-L55

I hope this helps.
