### ISSUE TITLE
Bug with multicarret (rectangle selection) delete

### ISSUE THREAD

**Issue by CarefreeCloud** [icsharpcode/AvalonEdit#22]
If you try to delete symbols with multicarret (rectangle selection) while having 0 visual columns (by pressing backspace or del), you will have your selection flushed back to single line carret and only 1 symbol will be deleted.
Back in 4.3.1 everything was fine with it

**Comment by zaksmolen** [comment]
This is definitely still an issue. If you block select multiple lines and 1+ columns and backspace, that backspace effects all lines, as expected. If you block select multiple lines with 0 columns (such as by holding alt+shift and arrow key down a few times) and then backspace, only one line in that selection will have that backspace. For example, in the following text:

`abc|def
abc|def
abc|def
abc|def`

Assuming that the space between the c's and d's is selected, you would think that backspace would erase all c's but instead it will only erase the c from one line. Erasing all lines is the behavior you'd expect, and standard among every editor I have seen with block select mode. Text entry does work. In the above case, if you type any character it is added to all lines, but if you then press backspace that character is removed from only one line...
