### ISSUE TITLE
Avalon wont let you type

### ISSUE THREAD

**Issue by ghost** [icsharpcode/AvalonEdit#225]
it wont let you type anything if the window freezes and unfreezes
everything works but not typing

**Comment by heartacker** [comment]
hi ，what ls your netcore version？
I have the same problem .It work well in the pre netcore version In my dim memory.

**Comment by siegfriedpammer** [comment]
Is this still a problem using recent versions of WPF Core? If so, please post a minimal repro. Thanks!
