### ISSUE TITLE
Keyboard input while CompletionWindow is open.

### ISSUE THREAD

**Issue by svenrog** [icsharpcode/AvalonEdit#227]
It is not currently possible to press home or end with a CompletionWindow open, making it impossible to shift select the entire row quickly. This is possible while the window is closed and while open in IDEs featuring similar functionality, like Visual Studio Code.

**Comment by wanglong126** [comment]
I have encountered a similar problem. When the completionwindow is null, you can use the shortcut key. However, if the completionwindow is not null, the shortcut keys such as home and end cannot be used

**Comment by siegfriedpammer** [comment]
Yes, this is currently by design. You are welcome to modify the behavior, by forwarding these special keys from the completion window the text editor and provide a pull request. Thanks!
