### ISSUE TITLE
AvalonEdit TextDocument crash reading large files

### ISSUE THREAD

**Issue by zaksmolen** [icsharpcode/AvalonEdit#229]
I have an editor implemented using `AvalonEdit`, and when I open a new file I populate the `Document` with a new `TextDocument`, and populate that `TextDocument` with an `IEnumerable<char>`. That `IEnumerable` is just reading the file, char-by-char, from a stream.

We recently had it crash when opening a large file. Large meaning 600MB of plaintext. Don't ask, I think it's ridiculous, but it's necessary to be able to view files that big for our application. After a bunch of debugging, I found that the `TextDocument` constructor is crashing with an `OutOfMemoryException`, specicifically something where "Array dimensions exceeded supported range." Here's the relavent part of the stack trace:

    System.OutOfMemoryException: Array dimensions exceeded supported range.
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at ICSharpCode.AvalonEdit.Utils.Rope`1.ToArray(IEnumerable`1 input)
       at ICSharpCode.AvalonEdit.Utils.Rope`1..ctor(IEnumerable`1 input)
       at ICSharpCode.AvalonEdit.Document.TextDocument..ctor(IEnumerable`1 initialText)
       ...

In my debugging I found that it happened consistently on the 134217728th character (2^27). That seems like an arbitrary limit, is there any reason that this would be a restriction? I'd expect the restriction of an array length to be `int.MaxValue`. It looks like it's something to do with the Rope creation, but I haven't been able to go too deep into the `Rope<T>` source code yet. From what I saw, it's calling the Linq extension method `ToArray()` which should theoretically have a max size of `int.MaxVal`

**Comment by dgrunwald** [comment]
The first thing the `Rope` constructor does it call LINQ `ToArray()` on your enumerable. It seems like that's already crashing here.
Can you try calling `.ToArray()` on your enumerable without using AvalonEdit, to see if that results in the same error?

**Comment by zaksmolen** [comment]
Interesting, as expected I do get a crash just trying to `.ToArray()` my enumerable. I'll try and look into that and figure out why that's the case. The enumerable in question here is basically just a function that opens a stream for the file and yield-returns each character. I found I had to do that a few years ago for larger files, but I wonder if that is adding some overhead that's messing with the limits. The theoretical max array size should be int.MaxVal which is around 2GB worth of ascii text.

**Comment by zaksmolen** [comment]
I had originally done the yield return thing because I had some files that were too large for a string to hold. I tried a bunch of different things, but can't get any to work. Oddly enough, I can actually allocate a `char[]` with the full file length (300+ MB) and populate it that way. But even though it's currently an array, it still fails a new .ToArray() call. I tried lots of different methods with streams and such. Just reading the file into a string (or making a string from my allocated char array) fails with memory exceptions as well.

This isn't an especially low memory machine, I have 8GB. It's interesting that it's failing on the 2^27th character in a bunch of methods I tested. I'm wondering if the issue there isn't actually the 2^27th character, but dynamically resizing things (usually by doubling size) so it's having trouble allocating a 2^28th length array.

Anyway, this seems more like a "text is too long for C# strings" issue so I might just throw some size limit checks in there, and prevent them from opening especially large files. It's odd though that if I pass in a `char[]` it still calls linq's `ToArray()`, because looking at the code, it seems like it does a cast first and the `as T[]` shouldn't be null and therefore I'd expect it to not call that method.

**Comment by dgrunwald** [comment]
Are you running on a 32-bit runtime? In 32 bits, address space fragmentation may prevent you from allocating large arrays.
But 64 bits should be able to deal with an array this size, especially if you enable `gcAllowVeryLargeObjects`.

**Comment by zaksmolen** [comment]
64-bit, and I tried that flag as well with no difference. I also tried
right after a fresh restart, so hopefully my memory was as uncluttered as
possible, with no change.

**Comment by zaksmolen** [comment]
So I just restarted my machine again, and made sure to close down everything I can (though as this is my work machine I can't close a lot of stuff). I also double checked and this machine has 16GB of ram. I was able to open the full 340MB file successfully. My application was using <100MB of memory before I opened the file, and 3.2GB of memory after opening it. 
I'm not sure what the factor of 10 increase is, but it seems like purely a legitimate "memory available" issue. Not sure why it was so consistent at first, but it sounds like I just need to catch some OutOfMemoryExceptions and don't need to worry about thresholds or any of that.

**Comment by zaksmolen** [comment]
I'll add that I fiddled around with this a bit more, and came up with something that did improve things a bit:
`            
            char[] charArray = getFileAsCharArray(filename, _isReadOnly);
            Rope<char> textRope = new Rope<char>(charArray, 0, charArray.Length);
            TextDocument document = new TextDocument(textRope);
`
By making the `Rope` explicitly, and then making the `TextDocument` from it, I assure that we aren't creating a duplicate, calling the Linq function, and so on. Also, while it takes more memory up front, reading to a char array seems to be faster and more efficient than something that goes character-by-character because I can do it in one block read.

I still might not be able to allocate the full char array if the file is truly massive, but this seemed a little faster and more stable than working off my enumerator with yield returns.
