### ISSUE TITLE
How can I set the line height outside?

### ISSUE THREAD

**Issue by LouisHQ** [icsharpcode/AvalonEdit#233]
How can I set the line height outside? Thanks~

**Comment by siegfriedpammer** [comment]
Does setting `textEditor.TextArea.TextView.DefaultLineHeight` solve your problem or do you mean something else? Thank you!

**Comment by ArunPatal** [comment]
Hello, I am interested to know if we can set DefaultLineHeight value?
So that there is enough space between each line (just like line-height property in css).
I am using 5.0.4

**Comment by siegfriedpammer** [comment]
Unfortunately, no. Sorry, I was wrong when writing my last answer. This is not possible, because we derive the text height from the font.

See https://github.com/icsharpcode/AvalonEdit/blob/8090219cd6407e34c691d1351114e94dea2f23f5/ICSharpCode.AvalonEdit/Rendering/TextView.cs#L1554-L1578
