### ISSUE TITLE
AvalonEdit showing null characters at the end of large file

### ISSUE THREAD

**Issue by zaksmolen** [icsharpcode/AvalonEdit#238]
We have the potential for some large text files, which has caused a few issues with AvalonEdit over the years, some still unresolved. But we just recently found this new one. For some reason, this specific file displays around 18 "NUL" characters at the end of the file. I can delete them, and when I reopen the file they're still there. If I put text after the NULs, and delete the NULs, the new NULs when I reopen the file are after the text I added, i.e. always at the end of the file.

When I open the file in NP++ or other similar editors, I don't see anything at the end of the file. This seems to just be NUL characters that are displayed in AvalonEdit, but don't actually exist in the file. I have attached an image of what's going on. As you can see, it's a decently-long file. I can't share the file since it's all proprietary data, but I will try and see if I can make a similar test file, to determine if it's length or specific file content that's triggering this. In the past when working on other AvalonEdit large file issues I never saw this, so I expect it's not just tied to file length. Also this behavior seems consistent, with multiple users seeing it on different machines.

![image](https://user-images.githubusercontent.com/12516896/83690618-0afe5c80-a5bf-11ea-8510-b7314a29c161.png)

**Comment by jimfoye** [comment]
What is the actual encoding of the file, and what does AvalonEdit think it is?

**Comment by zaksmolen** [comment]
Encoding is ANSI. In some cases I get strings of content, some files are remotely hosted and contents are retrieved with web protocols, and in those cases I just set `Document.Text` to that string.

In order to read local files, I read the file into a `char[]` and then create a rope from that myself, then create a `TextDocument` with that rope. That was the best way I could find to deal with extremely large files, since 300+MB text files, while obscenely large, are not unheard of in our application. I used to create the `TextDocument` from an `IEnumerable<char>` which was just yield returning each character, but that kept too much in memory for large files and would cause out of memory crashes.

In testing today, I was able to see that it is actually adding the NUL characters to the end of the file every time I open. When I saved the file without deleting them, I got them to show up in NP++. Every time I open up the file it seems to add 18 NULs to the end. I started with 18, open, save, it has 36 (confirmed in NP++). Open, save, open, save, I'm at 72.

I can delete the NULs and save, and it persists fine. But if I open the file again, it will add 18 new NULs and so on. I have attached a screenshot showing the end of the file in Notepad++ after I deleted all NULs, opened the file in my application (which added the NULs), and saved it. Encoding, file length, and other information like that can also be seen.

![image](https://user-images.githubusercontent.com/12516896/83812952-68abab00-a68a-11ea-8748-7972d400b392.png)

**Comment by jimfoye** [comment]
What does AvalonEdit think the encoding is?

**Comment by zaksmolen** [comment]
Sorry about that, I thought I included that info. When I checked, `Encoding` was null. So I assume whatever the default is?

**Comment by jimfoye** [comment]
When AvalonEdit opens a file and you haven't specified an encoding, it makes a best guess. Try setting the Encoding property on the TextEditor to Windows-1252 (which you can get with 

`Encoding.GetEncoding(1252);`

before loading the file.

**Comment by zaksmolen** [comment]
That did it! Thank you very much for the fix. Any idea what would cause the NULs? Does that mean something like I have 18 odd characters in my file that I should search for?

**Comment by jimfoye** [comment]
"NUL" is what AvalonEdit uses to display a character with the value of 0. If you want to dig further, I'd suggest first examining more closely what exactly is hiding at the end of your file (use an editor that will display what's there in hex). If matters still aren't clear, download the AvalonEdit source and build and debug to determine exactly how it's handling those bytes.
