### ISSUE TITLE
WPF APP will hang if the editor SyntaxHighlighting=python

### ISSUE THREAD

**Issue by heartacker** [icsharpcode/AvalonEdit#241]
OS: Windows_NT x64 10.0.14393
dotnetcore: 3.1.301
my wpf app is a editor using Avalonedit.
when setting the highlight==python(py). my wpf app hang, the only thing I can do is  kill it by force.
but it works well when SyntaxHighlighting is not python, like markdown, csharp an so on.

**Comment by heartacker** [comment]
there is the pic.
it seems that all SyntaxHighlighting will casuse the app-hang,
![editor2](https://user-images.githubusercontent.com/1876302/87287921-43357b00-c52d-11ea-8959-666b9f2c20ee.gif)
and also, it will hang if text length >5

**Comment by heartacker** [comment]
I download the source code, and add it to my project.
there is the code the cause  the hang.
![Snipaste_2020-07-13_17-50-51](https://user-images.githubusercontent.com/1876302/87291318-b8a34a80-c531-11ea-86a8-e1352e5151be.png)

**Comment by heartacker** [comment]
hi，it seem that this problem has some to do with  highlighted-rule,
eg: work well while input mcu.Core and hang when input `impor`
![image](https://user-images.githubusercontent.com/1876302/88145497-110ed200-cc2d-11ea-854d-197212c7dbe2.png)

**Comment by siegfriedpammer** [comment]
I just tried to reproduce this using a project targetting net5.0. I was unable to reproduce it. Is this still a problem using recent net5.0? Thanks!

**Comment by heartacker** [comment]
> I just tried to reproduce this using a project targetting net5.0. I was unable to reproduce it. Is this still a problem using recent net5.0? Thanks!

thanks, finall we have found that i upgrade my embed-font `Cascadia Code`which caused this issues. there is nothing
 to do with avalonedit. thanks
