### ISSUE TITLE
Building a solution in VS2019 including AvalonEdit: Github shows changes in AvalonEdit source code when no changes were made

### ISSUE THREAD

**Issue by Joe-Blaze** [icsharpcode/AvalonEdit#245]
In a solution which includes application code that is dependent on AvalonEdit and also includes the AvalonEdit source code project, whenever the application code project is built, Github: Changes in VS2019 Team Explorer always indicates changes made in the AvalonEdit project when none were made.  Examining the supposed changes show no changes were made.

Not a critical issue, but curious if any user has an explanation.

**Comment by siegfriedpammer** [comment]
Which change do you speak of? We currently only know of the ICSharpCode.AvalonEdit.xml which is (erroneously) generated in the root folder of the project.

**Comment by Joe-Blaze** [comment]
My comment was based on the ICSharpCode.AvalonEdit.xml generation.  When this file is re-built it is detected by GitHub in VS2019 v16.9.0 and prior.

**Comment by christophwille** [comment]
Fixed via https://github.com/icsharpcode/AvalonEdit/commit/be12b1609de8839894e05a5b4cc817a85879f940
