### ISSUE TITLE
Support for WinUI

### ISSUE THREAD

**Issue by soumyamahunt** [icsharpcode/AvalonEdit#248]
MS is unifying UI framework for windows with WinUI. Is there any plan to support WinUI 3??

**Comment by jimfoye** [comment]
Next year it will be something else.

**Comment by christophwille** [comment]
We are tied to WPF - and have netcore as part of the NuGet package already today. Rewriting for a different platform is definitely not planned (I know next to nothing about WinUI - because who cares about what the Windows division does)
