### ISSUE TITLE
Support for .Net 5

### ISSUE THREAD

**Issue by JanTamis** [icsharpcode/AvalonEdit#250]
Are there any plans to support .Net 5?

**Comment by christophwille** [comment]
We have a 3.1 target. Isn't that sufficient?

**Comment by JanTamis** [comment]
i would like to update my program to use .Net 5, in which i use avalonedit

**Comment by jim-lightfoot** [comment]
My app is .Net 5 and I use AvalonEdit without any issues.

**Comment by jim-lightfoot** [comment]
I should clarify and say I am using the NuGet package.

**Comment by JanTamis** [comment]
I've tested it and it indeed works.
