### ISSUE TITLE
Performance of Fonts?

### ISSUE THREAD

**Issue by goswinr** [icsharpcode/AvalonEdit#252]
What fonts are you recommending with Avalonedit?
I noticed an editing lag in my editor.
To my surprise by switching the font from [`Fira Code`](https://github.com/tonsky/FiraCode) to [`Consolas `](https://en.wikipedia.org/wiki/Consolas)I got significant improvements. 
Are there any font rendering settings that I can tweak in Avalonedit?
(Another reason for the lag is my elaborate F# syntax highlighting definition (xshd), but this is probably more difficulty to improve.)

**Comment by siegfriedpammer** [comment]
Thanks for asking, however, we never did analyze the performance of newer fonts. However, there is a recent trend to use fonts with lots of ligatures for all sorts of operators used in programming. We have never tried this on our own, however, there were reports (see #241) that these fonts cause bad performance in WPF. Currently, we only can recommend to NOT use any special fonts until Microsoft fixes these rendering performance issues. Hope this helps!
