### ISSUE TITLE
Filter CompletionWindow as user types

### ISSUE THREAD

**Issue by Thaval** [icsharpcode/AvalonEdit#256]
Hi,

when I have a CompletionWindow with about 80 elements and the user starts typing, I want to reduce the number of results, respectively to the elements the user typed filtered with criteria "startsWith".
Here is my implementation:

 ```
private string _searchCompletionWindow = string.Empty;
        private void TextArea_TextEntering(object sender, TextCompositionEventArgs e)
        {
            if (e.Text.Length > 0 && completionWindow != null)
            {
                if (!char.IsLetterOrDigit(e.Text[0]))
                {
                    completionWindow.CompletionList.RequestInsertion(e);
                }
                else
                {
                    _searchCompletionWindow += e.Text;
                    var toBeCleared = completionWindow.CompletionList.CompletionData.Where(x => !x.Text.StartsWith(_searchCompletionWindow, StringComparison.InvariantCultureIgnoreCase)).ToList();
                    toBeCleared.ForEach(x => completionWindow.CompletionList.CompletionData.Remove(x));
                }
            }
        }
```

The problem is that the completion window gets cleared when the user types, but I can see that the "toBeCleared" variable has elements, for example 7. If I first type and then open the completion window, all 7 entries are shown.

How can I achieve filtering while typing?

**Comment by siegfriedpammer** [comment]
I cannot give you an answer specific to your problem, but we had similar functionality in SharpDevelop, so you could take a look at its implementation (see https://github.com/icsharpcode/SharpDevelop/blob/master/src/AddIns/DisplayBindings/AvalonEdit.AddIn/Src/CodeEditor.cs#L506-L586) and experiment with the properties of `CompletionWindow`. Hope this helps!
