### ISSUE TITLE
Issue on hyperlinks, they are trying to open in the application

### ISSUE THREAD

**Issue by simonatocanie** [icsharpcode/AvalonEdit#259]
On Wpf Application, on the  <avalonEdit:TextEditor> the hyperlinks are displayed propertlly, but on CTRL + Click they are trying to open inside in the application.  In wpf application, the links inside <Hyperlink> are open in browser, and all working well.

The behaviour that I want to achieve is to open in the browser, not inside in the wpf application. This will be possible?

If this not posibble, there is a way to display the links as text, not as hyperlinks? - This i solved it - EnableHyperlinks = false

I attached you some picture.

![image](https://user-images.githubusercontent.com/43148857/107011104-dff88800-679f-11eb-9f1c-3125fb0bb7bd.png)

![image](https://user-images.githubusercontent.com/43148857/107011132-eab31d00-679f-11eb-969b-42443da755ef.png)

Thank you,
Simona

**Comment by siegfriedpammer** [comment]
Sorry, I do not fully understand what you want to do. WPF applications do not come with an embedded browser. The thing you want to achieve should already be the default. Have you tried the AvalonEdit.Sample application? Do you see the same erroneous behavior there? Thanks!
