### ISSUE TITLE
The current node attributes will be hided when folding a node in XML

### ISSUE THREAD

**Issue by kaifuzi** [icsharpcode/AvalonEdit#262]
The current node attributes will be hided when folding a node in XML, is it possible to keep the current node attributes visible?
Thanks!

**Comment by siegfriedpammer** [comment]
No, this is not possible using the built-in XML folding strategy, however, you could always implement a custom folding strategy by copying the code and modifying it to match your requirements.

See https://github.com/icsharpcode/AvalonEdit/blob/a5691facdde5d06c3de50118c9894970d709ea55/ICSharpCode.AvalonEdit/Folding/XmlFoldingStrategy.cs

Hope this helps!
