### ISSUE TITLE
Multiples Column Ruler

### ISSUE THREAD

**Issue by bencz** [icsharpcode/AvalonEdit#266]
Hi
It's possible to define multiples Column Ruler Position for the same text editor ?

**Comment by siegfriedpammer** [comment]
No, this is not possible using the built-in column ruler renderer. However, you could copy the code and add multiple rulers manually. See https://github.com/icsharpcode/AvalonEdit/blob/a5691facdde5d06c3de50118c9894970d709ea55/ICSharpCode.AvalonEdit/Rendering/ColumnRulerRenderer.cs and also

https://github.com/icsharpcode/AvalonEdit/blob/a5691facdde5d06c3de50118c9894970d709ea55/ICSharpCode.AvalonEdit/Rendering/TextView.cs#L71

https://github.com/icsharpcode/AvalonEdit/blob/a5691facdde5d06c3de50118c9894970d709ea55/ICSharpCode.AvalonEdit/Rendering/TextView.cs#L223-L226

https://github.com/icsharpcode/AvalonEdit/blob/a5691facdde5d06c3de50118c9894970d709ea55/ICSharpCode.AvalonEdit/Rendering/TextView.cs#L2039-L2041
