### ISSUE TITLE
How to add breakpoints in AvalonEdit?

### ISSUE THREAD

**Issue by Return25** [icsharpcode/AvalonEdit#280]
I want to add breakpoints to AvalonEdit like Visual Studio. 
Can AvalonEdit do it?
If AvalonEdit can do it, how can I do it?
Thanks.

**Comment by siegfriedpammer** [comment]
Please take a look at SharpDevelop's source code. It implements this feature:

* https://github.com/icsharpcode/SharpDevelop/blob/master/src/AddIns/DisplayBindings/AvalonEdit.AddIn/Src/CodeEditor.cs#L241 (for the "installation")
* https://github.com/icsharpcode/SharpDevelop/blob/master/src/AddIns/DisplayBindings/AvalonEdit.AddIn/Src/IconBarMargin.cs (the implementation of the actual margin)

Hope this helps!
