### ISSUE TITLE
Center Text

### ISSUE THREAD

**Issue by gnimor** [icsharpcode/AvalonEdit#281]
Sorry for this stupid question I read a lot in the documentation but perhaps I miss the forest for the trees. I just want to center my text - is this easily possible?

**Comment by siegfriedpammer** [comment]
As far as I know, this is currently not possible.

**Comment by jimfoye** [comment]
Looks like someone took a stab at this years ago, see this question on SO: https://stackoverflow.com/questions/23983463/how-to-center-text-in-avalonedit

**Comment by siegfriedpammer** [comment]
AvalonEdit is not a `RichTextBox`. See also my comment https://github.com/icsharpcode/AvalonEdit/issues/303#issuecomment-997850791
