### ISSUE TITLE
WorkaroundWPFMemoryLeak

### ISSUE THREAD

**Issue by jimfoye** [icsharpcode/AvalonEdit#284]
Does anyone know the history behind this workaround? Maybe Microsoft changed or fixed this in some later version of the framework?

**Comment by siegfriedpammer** [comment]
For those who wonder what this is about: see the following code: https://github.com/icsharpcode/AvalonEdit/blame/master/ICSharpCode.AvalonEdit/Editing/TextAreaDefaultInputHandlers.cs#L71-L79

**Comment by jimfoye** [comment]
I just did a test with DotMemory from JetBrains. I'm still pretty new to this tool, but I just looked at memory snapshots after closing the editor with this code in place and then again with it removed. In the latter instance, DotMemory is showing an instance of TextDocument still in memory. This is .NET Framework 4.7.2. So I guess that answers my question :disappointed:
