### ISSUE TITLE
AST Based Highlighter

### ISSUE THREAD

**Issue by mike-ward** [icsharpcode/AvalonEdit#29]
Is it possible to implement a highlighter based on something other than Regex (an AST for instance)? The current `IHighlightDefinition` appears to only work wth Regex.

**Comment by dgrunwald** [comment]
`IHighlightDefinition` is a set of rules for the built-in regex based highlighters. You can use an AST-based highlighters by implementing `IHighlighter` yourself; or alternatively, by implementing a `DocumentColorizingTransformer`. (`IHighlighter` has the advantage that the highlighting is also kept when copying the text to the clipboard in HTML format)

For example, this is the semantic C# highlighter used in SharpDevelop: https://github.com/icsharpcode/SharpDevelop/blob/master/src/AddIns/BackendBindings/CSharpBinding/Project/Src/CSharpSemanticHighlighter.cs
