### ISSUE TITLE
WinUI Port

### ISSUE THREAD

**Issue by NeomMob** [icsharpcode/AvalonEdit#290]
Do you have plan to port it to WinUI(3)? 
I am wondering what would be the effort for a such port and how we could help on this.

**Comment by christophwille** [comment]
See #248

**Comment by NeomMob** [comment]
Thanks, sorry for the duplicate

**Comment by blakepell** [comment]
If you're interested in the kinds of changes that would have to be made you might take a look at the port the Avalonia folks were/are working on as a road map.  You might find some useful tidbits there.

Sent from my iPhone

On Jun 29, 2021, at 9:39 AM, NeomMob ***@***.***> wrote:

﻿

Thanks, sorry for the duplicate

**Comment by lextm** [comment]
A Uno/WinUI 3 port is finished as mentioned #447 and will be shipped as a separate project named [UnoEdit](https://github.com/lextudio/UnoEdit).
