### ISSUE TITLE
Syntax Highlighting problem

### ISSUE THREAD

**Issue by NotroDev** [icsharpcode/AvalonEdit#291]
Hey, I have a problem. I am doing my own syntax highlighting and needed to color the word "on". Now, when I try to color the word, for example, "permission", only the ending, on, is colored. How can I fix it?

Permission and "on" code:
https://imgur.com/a/hWE2SxM

**Comment by siegfriedpammer** [comment]
The `Begin` and `End` elements support regular expressions, so you should be able to do something like `<Begin>\bon</Begin>`.

**Comment by NotroDev** [comment]
> The `Begin` and `End` elements support regular expressions, so you should be able to do something like `<Begin>\bon</Begin>`.

Hey! Sorry for late reply, but this is working! Very thanks!
