### ISSUE TITLE
JSON syntax highlighter please!

### ISSUE THREAD

**Issue by calloncampbell** [icsharpcode/AvalonEdit#30]

**Comment by dgrunwald** [comment]
We currently don't plan to develop any new features for AvalonEdit. Feel free to submit a pull request if you feel that something should be added to AvalonEdit.

In the particular case of JSON, couldn't you just use the JavaScript highlighter instead?

**Comment by wonea** [comment]
There's a definition here [AvalonEdit - xshd for JSON highlighting](https://stackoverflow.com/a/33309923/271200)

```
<?xml version="1.0" encoding="utf-8" ?>
<SyntaxDefinition name="Json" extensions=".js" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
  <Color name="Digits" foreground="#8700FF" exampleText="3.14" />
  <Color name="Value" foreground="#000CFF" exampleText="var text = &quot;Hello, World!&quot;;" />
  <Color name="ParamName" foreground="#057500"  exampleText="var text = &quot;Hello, World!&quot;;" />
  <RuleSet ignoreCase="false">
    <Keywords color="Digits" >
      <Word>true</Word>
      <Word>false</Word>
    </Keywords>
    <Span color="ParamName">
      <Begin>"</Begin>
      <End>(?=:)</End>
    </Span>
    <Span color="Value" multiline="true">
      <Begin>
        (?&lt;=:)\040"[^"]*
      </Begin>
      <End>"</End>
    </Span>
    <Rule color="Digits">\b0[xX][0-9a-fA-F]+|(\b\d+(\.[0-9]+)?|\.[0-9]+)([eE][+-]?[0-9]+)?</Rule>
  </RuleSet>
</SyntaxDefinition>
```

**Comment by Kabennsky** [comment]
Thank you for posting your solution :) I am driving crazy with the regex in AvalonEdit it sometimes seems to  react different to other regex matcher.

Is there a way for the ParamName to only highlight the name without the " around it??
"ParamName" => only ParamName highlighted not the whole "ParamName"
