### ISSUE TITLE
Search Panel style doesn't work

### ISSUE THREAD

**Issue by NotroDev** [icsharpcode/AvalonEdit#302]
hey idk why, but when i copy the xaml code of the search panel I have errors like "no searchpanel in search"...

[Code](http://hastebin.com/asekugonow.xml)

Errors:
![Errors](https://i.imgur.com/qnlGUsU.png)

**Comment by siegfriedpammer** [comment]
Copying XAML code without adjusting the namespaces of code-behind classes and XAML references usually leads errors like this. Were you able to resolve this?
