### ISSUE TITLE
I want to replace RichTextBox text with this

### ISSUE THREAD

**Issue by dzx815** [icsharpcode/AvalonEdit#303]
I want to add colored text by        _avalonEdit.TextEditor.AppendTxt("test",Brushes.Red )_

It is used to display some prompts, because the performance of this is much higher than that of RichTextBox.

But I haven't found such an interface yet. Can you help me?

**Comment by goswinr** [comment]
I also wanted such an interface. So i implemented it my self:
https://github.com/goswinr/AvalonLog Maybe you can use that one.

**Comment by dzx815** [comment]
Thank you for your reply.
But this is F#, I want C# code.

**Comment by dzx815** [comment]
Thank you for your reply.
This is indeed possible, but I still want to see if there is any C#.

This is indeed ok, but I still want to see if there is C#, F# outputs a series of files

![image](https://user-images.githubusercontent.com/15151459/131822957-412968b5-a070-4ac6-91ac-5349696a0bfa.png)

**Comment by dzx815** [comment]
I am not just because of these additional files, because I also want to make some changes, such as controlling whether to scroll to the bottom, etc.

If there are no other controls, I might try to rewrite your process with c#。

**Comment by goswinr** [comment]
If you just want to control scrolling open an issue or PR at https://github.com/goswinr/AvalonLog and we discuss it there..

**Comment by dzx815** [comment]
I have roughly rewritten what I need to use, but I found a bug at present. If you insert a string in the middle of a string of multiple colors, it will cause the subsequent color display to be completely confused.

myCode=
private void Button_Click(object sender, RoutedEventArgs e)
        {
            new Thread(() => {
                this.Dispatcher.Invoke(new Action(() => {
                    avlog.AppendWithBrush(Brushes.Red, "1");
                    avlog.AppendWithBrush(Brushes.Black, "2");
                    //avlog.AppendWithBrush(Brushes.Red, "3");
                }), null);
            }).Start();
        }

![image](https://user-images.githubusercontent.com/15151459/132082496-d0469a47-e2ca-44aa-9631-b73a72e603ed.png)

![image](https://user-images.githubusercontent.com/15151459/132082520-5f61d678-1f45-485c-aa38-913ac2fef322.png)

**Comment by goswinr** [comment]
@dzx815 see my answer here: https://github.com/goswinr/AvalonLog/issues/1

**Comment by siegfriedpammer** [comment]
I am fairly certain that AvalonEdit is not the right tool for the job. A `RichTextBox` has features that cannot be mimicked using AvalonEdit. Firstly, AvalonEdit supports only one single font for the whole document and secondly, the highlighting is rule-based and not as with rich text editors like Word based on user input. Implementing these features on top of AvalonEdit is a lot of work, bordering "impossible to get right".
