### ISSUE TITLE
Provide better ability to theme the editor (light/dark)

### ISSUE THREAD

**Issue by calloncampbell** [icsharpcode/AvalonEdit#31]
AvalonEdit is a great editor but is not keeping up with the times. AvalonEdit should provide better theme support for Light and Dark themes. If this is something that is not deemed necessary, could someone at least explain how I could go about skinning the editor in a dark theme (see VS 2013 Dark theme as an example).

**Comment by thomasjoscht** [comment]
+1 for this. I've seen some implementations of further highlighting theming in Notepad++ and Edi sources. But they aren't easy to transfer and therefore not easy to use.

**Comment by shadeMe** [comment]
Doesn't changing the TextEditor's Foreground and Background brushes work to that effect?

**Comment by christophwille** [comment]
Are you looking for a feature like this?

http://community.sharpdevelop.net/blogs/christophwille/archive/2012/08/13/import-and-export-of-highlighting-settings.aspx

**Comment by calloncampbell** [comment]
This is nice...no I mean theme the entire editor, not just the contents. This includes the editor controls like scroll bars, buttons, background (that I can do now), etc.

Visual studio supports dark theme, everything is dark. Now if avalonedit were to be used inside an app that supports dark, everything but avalonedit would be dark. I want avalonedit to support dark.

Callon

Sent from my Windows Phone
________________________________

**Comment by calloncampbell** [comment]
Yes but not for the entire editor UI. Scrollbars are still standard battleship gray. If those could be exposed to change the colors...great...or support for an entire theme file, where I can customize the colors etc for the control...awesome.

Thanks
Callon

Sent from my Windows Phone
________________________________

**Comment by calloncampbell** [comment]
Here is an example of what I mean…notice the scrollbars are gray…


 






Sent from Windows Mail





From: Madeesh Kannan
Sent: ‎Friday‎, ‎March‎ ‎20‎, ‎2015 ‎5‎:‎08‎ ‎AM
To: icsharpcode/AvalonEdit
Cc: Callon Campbell





Doesn't changing the TextEditor's Foreground and Background brushes work to that effect?

**Comment by calloncampbell** [comment]
Here is an example of what I mean…notice the scrollbars are gray…


 






Sent from Windows Mail





From: Christoph Wille
Sent: ‎Friday‎, ‎March‎ ‎20‎, ‎2015 ‎5‎:‎15‎ ‎AM
To: icsharpcode/AvalonEdit
Cc: Callon Campbell





Are you looking for a feature like this?

http://community.sharpdevelop.net/blogs/christophwille/archive/2012/08/13/import-and-export-of-highlighting-settings.aspx

**Comment by thomasjoscht** [comment]
Theming controls is easy to implement with styles out of sources. Main interesting feature is dependent Highlighting Colors from theming color. Like VS 2013 highlighting colors must be little lighter in Dark Theme then in Light Basic Theme otherwise highlighting colors are difficult to recognition. Therefore it must be possible to have one highlighting color definition per theme per language (f.e. sql) or the highlighting colors per language must be defined dynamic (like DynamicResources). This is f.e. possible with Edi https://edi.codeplex.com/. Problem there is that the implementation isn't easy to port in own application.

**Comment by calloncampbell** [comment]
I posted a link to a screenshot to show you what I mean:
https://twitter.com/flying_maverick/status/578877401217675265/photo/1

Yes ThomasJoscht, I could use styles...but when I looked at Edi project, their using AvalonEdit source directly and injecting styles. The styles got messay because some are his own and others are from MUI project. Final result is that it works for him. I would prefer that the control had support for this natively so that I can tell it light or dark or pass in a style without using the source. I prefer to just use the DLL.

What would happen if SharpDevelop wanted to support a dark theme for the entire IDE? 

Anyway I'm just looking for some direction to do this cleanly.

Thoughts?

**Comment by thomasjoscht** [comment]
Predefined themes for AvalonEdit isn't a solution in my case because theming is controlled by other framework (MahApps.Metro) inkl. Color and Style definition which I will or must reuse. Also custom theming (and accenting) will not possible with predefined mechanismn. Best will be an extendable and dynamic solution with 2 sample themes (Light and Dark). Nevertheless dynamic highlighting syntax color definion will be main part because this isn't supported yet at all.

**Comment by dgrunwald** [comment]
There won't be any predefined styles shipping with AvalonEdit.

AvalonEdit should expose all brushes and pens as properties, use WPF styles to set those properties if you need to re-style the control. Also note that `TextEditor` really is just a wrapper control that puts a `TextArea` in a regular `ScrollViewer` and provides a `TextBox`-like API. If you need more control, you can overwrite the `TextEditor` control template, or just skip using `TextEditor` entirely and directly use `TextArea`.

**Comment by GreatFireWall** [comment]
> Are you looking for a feature like this?
> 
> http://community.sharpdevelop.net/blogs/christophwille/archive/2012/08/13/import-and-export-of-highlighting-settings.aspx

I want to ask is there a built-in property for switch dark/light theme of TextEditor?
Now I use `TextEditor` and `Mahapp.Metro` together, the latter offers a dark theme, so you will see the follow:

![image](https://user-images.githubusercontent.com/4510984/66659123-6e74fc00-ec75-11e9-9174-bb763783c8db.png)

The black words is hard to read..
