### ISSUE TITLE
Wrong Folding When Brace Is Within Comment

### ISSUE THREAD

**Issue by ArunPatal** [icsharpcode/AvalonEdit#312]
Hello,
When closing brace is inside comment, it folds till there.
Please see photo.

![folding](https://user-images.githubusercontent.com/30784805/137911733-cdca2d90-d2c2-4bd2-8f08-56d32cf3f32b.png)

**Comment by siegfriedpammer** [comment]
Yes, that is because the default logic for brace folding has no language-awareness whatsoever. It simply doesn't recognize or even care about comments. You will have implement your own parser-based folding strategy.
