### ISSUE TITLE
Changing Line Height

### ISSUE THREAD

**Issue by ArunPatal** [icsharpcode/AvalonEdit#315]
Hello,

I was searching to set height of each line but could not found much..

Found two related topics

[https://stackoverflow.com/questions/39446610/change-line-height-in-avalonedit-5-x](https://stackoverflow.com/questions/39446610/change-line-height-in-avalonedit-5-x)

[https://github.com/icsharpcode/AvalonEdit/issues/233](https://github.com/icsharpcode/AvalonEdit/issues/233)

Is there any inbuild option for this in 5.0.4?

**Comment by siegfriedpammer** [comment]
Unfortunately, no. Sorry, I was wrong when writing my last answer. This is not possible, because we derive the text height from the font.

See https://github.com/icsharpcode/AvalonEdit/blob/8090219cd6407e34c691d1351114e94dea2f23f5/ICSharpCode.AvalonEdit/Rendering/TextView.cs#L1554-L1578
