### ISSUE TITLE
SearchResultBackgroundRenderer doesn't highlight short search results correctly for proportional fonts

### ISSUE THREAD

**Issue by simon-vaz-innoveo** [icsharpcode/AvalonEdit#316]
Using the standard SearchPanel, if we are using a proportional font (like Segoe UI) instead of a monospaced one, we get the highlight rectangles like this:
![image](https://user-images.githubusercontent.com/75614646/139452030-cbed55ca-409d-42e7-9951-f1e86563c093.png)
The SearchResultBackgroundRenderer class hardcodes the CornerRadius of the geoBuilder to "3" that is used for the highlighting. If we could make this border radius configurable, setting it to 0 would give us proper highlighting for proportionate fonts also:
![image](https://user-images.githubusercontent.com/75614646/139452735-c0ae0fc0-abdf-454e-ba6c-7076944ea17a.png)

**Comment by siegfriedpammer** [comment]
@simon-vaz-innoveo would you be able to try the proposed changes in #329 and provide feedback? Thanks!

**Comment by simon-vaz-innoveo** [comment]
@siegfriedpammer , it works like a charm. Thanks for the fix. 👍
