### ISSUE TITLE
Can AvalonEdit v6.1.2.30 be used in a .NET5 project?

### ISSUE THREAD

**Issue by DennyOne** [icsharpcode/AvalonEdit#317]
It seems AvalonEdit will load in a .NET6 project but not .NET5.  I've been using the AvalonEdit control in a .NET Framework (4.8) project for years and the wonderful control has worked with no issues.  Recently my company is moving to .NET5 but they are not yet ready to move to .NET6. 

Is there a version of AvalonEdit that will work with .NET5?  I've tried a bunch of versions (via Visual Studio Package Manager) all the way back to v5.0.2 and none of them seem to work in a .NET5 project.  Does anyone know for sure v6.1.2.30 will work in a .NET5 project (maybe it's a config issue on my end). 

Thanks in advance for help!

**Comment by christophwille** [comment]
https://www.nuget.org/packages/AvalonEdit/ see the dependencies tab - yes, net5.0 is supported.

**Comment by christophwille** [comment]
We are keeping the .NET 5.0 target for the next release, but it will be removed in the future (5.0 is not an LTS release).
