### ISSUE TITLE
Wrong CompletionSegment performed when we start typing while part of text already selected.

### ISSUE THREAD

**Issue by dijkstra33** [icsharpcode/AvalonEdit#32]
Hello. We use auto-completion with your editor. It works fine. But when i start typing in text area while part of text already selected - CompletionSegment miss first character. So auto completion ignore first key typed in. Even your completion example works with this bug.
How to fix this?

**Comment by dgrunwald** [comment]
When opening a completion window, set the `CompletionWindow.StartOffset` and `EndOffset` properties to specify the initial completion segment.

**Comment by dijkstra33** [comment]
@dgrunwald, you suggest incorrect solution.
"my selected text" -> (press 'w') -> "w" (here I get opened completion window and it is become closed without my interruption next moment) -> (press 'r') -> "wr" (here it again open completion segment, but segment has only "r" letter inside) -> (press 'o') -> "wro" (here it has segment "ro")

Why we should manage this situation ourselves? Catch this silly "text selected" state and then move segment offsets in correct positions? This problem should be solved once for all of us inside library classes, not outside, I hope you understand.

Thank you, I am sorry for being rude.

**Comment by dgrunwald** [comment]
I'll have a look at the completion example.

Note that this usecase works fine in SharpDevelop.

**Comment by dijkstra33** [comment]
@dgrunwald, I reproduced this bug in a little project (VS-2012): https://www.dropbox.com/s/4xt51erlhy7qwdv/AvalonEditBugSample.zip?dl=0

You can see incorrect behaviour if you'll perform this actions:
(select part of text in text area) -> (press 'I')

**Comment by siegfriedpammer** [comment]
From my analysis this is because you are opening the completion window in the `TextArea.TextEntering` event, whereas the AvalonEdit sample application does so in the `TextArea.TextEntered` event handler. The completion window closes itself automatically, because the offsets are no longer visible after the text has been replaced.
