### ISSUE TITLE
ICSharpCode.AvalonEdit.dll targets a platform whose toolbox items cannot be enumerated dynamically

### ISSUE THREAD

**Issue by esohasl** [icsharpcode/AvalonEdit#338]
Unable to add AvalonEdit to toolbox. Visaul Studio 2022 and AvalonEdit latest version. I tried to add with nuget and compile from github
![6HW9](https://user-images.githubusercontent.com/102621738/160684285-92d099ac-8dd8-445a-bb53-89c1a7662f5f.png)

**Comment by KZProgRus2023** [comment]
I have the same problem.
