### ISSUE TITLE
OnDrop does not use Modified Text

### ISSUE THREAD

**Issue by mike-ward** [icsharpcode/AvalonEdit#35]
This is similar to a bug #18.

The text for pasting is acquired before the OnPaste event is raised. This does not allow event handlers to modify the pasted text. See `SelectionMouseHandler.cs` line 225. The text needs to be reacquired after the paste event is raised in case the event handler has modified the data object.

**Comment by akash3456** [comment]
Is there any chance of an example please???

**Comment by mike-ward** [comment]
Sure.

In the load:

    DataObject.AddPastingHandler(AvalonEditBox, OnPaste);

And the later:

    private void OnPaste(object sender, DataObjectPastingEventArgs e)
    {
        var isText = e.SourceDataObject.GetDataPresent(DataFormats.UnicodeText, true);
        if (!isText) return;
        var text = (string)e.SourceDataObject.GetData(DataFormats.UnicodeText);

        var dataObject = new DataObject();
        dataObject.SetData(DataFormats.UnicodeText, string.Format("<{0}>", text);
        e.DataObject = dataObject;
    }

To reproduce drag and drop an image from a web browser. By default, AE will paste the link in. I want to modify the paste text to be surrounded by less than, greater than symbols (`<link>`). This is for use in my Markdown Editor (http://mike-ward.net/markdownedit).

If I create a new dataobject (as per the example) and return it, the original dataobject's text is used, not the modified text.

I can achieve this now by canceling the paste command and issuing a new paste with the modified text. It works but feels a bit wrong.

Hope that clarifies the issue.

**Comment by mike-ward** [comment]
For reference, here's how I'm currently working around the issue:

https://github.com/mike-ward/Markdown-Edit/blob/master/src/MarkdownEdit/Controls/Editor.xaml.cs#L141
