### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by NotroDev** [icsharpcode/AvalonEdit#354]
Hi. I have this in my xaml for code highlighting:
```xaml
<Span color="String">
	<Begin>"</Begin>
	<End>"</End>
</Span>
```
And yeah, it's working. But, i want to add a rule that will override it.
Eg. i have a rule that highlights text between `{}`. And i want it to highlight in `""` too.
Like this:
![obraz](https://user-images.githubusercontent.com/77281214/178324093-4bb690da-2552-474f-8311-ea1e1b960653.png)

How can i do this?

**Comment by siegfriedpammer** [comment]
This is probably what you what:

```xml
<?xml version="1.0"?>
<SyntaxDefinition name="Custom Highlighting" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
	<Color name="Comment" foreground="Green" />
	<Color name="String" foreground="Blue" />
	<Color name="BracedExpression" foreground="Orange" />
	
	<RuleSet>
		<Span color="String" ruleSet="BracedExpressionRuleSet">
			<Begin>"</Begin>
			<End>"</End>
		</Span>

		<Import ruleSet="BracedExpressionRuleSet" />
	</RuleSet>

	<RuleSet name="BracedExpressionRuleSet">
		<Span color="BracedExpression">
			<Begin>{</Begin>
			<End>}</End>
		</Span>
	</RuleSet>
</SyntaxDefinition>
```

**Comment by NotroDev** [comment]
> This is probably what you want:
> 
> ```
> <?xml version="1.0"?>
> <SyntaxDefinition name="Custom Highlighting" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
> 	<Color name="Comment" foreground="Green" />
> 	<Color name="String" foreground="Blue" />
> 	<Color name="BracedExpression" foreground="Orange" />
> 	
> 	<RuleSet>
> 		<Span color="String" ruleSet="BracedExpressionRuleSet">
> 			<Begin>"</Begin>
> 			<End>"</End>
> 		</Span>
> 
> 		<Import ruleSet="BracedExpressionRuleSet" />
> 	</RuleSet>
> 
> 	<RuleSet name="BracedExpressionRuleSet">
> 		<Span color="BracedExpression">
> 			<Begin>{</Begin>
> 			<End>}</End>
> 		</Span>
> 	</RuleSet>
> </SyntaxDefinition>
> ```

Yes, it's working perfectly! Thanks! :D

**Comment by NotroDev** [comment]
Hey, sorry, but I have new problems...
This:
```xaml
<Keywords foreground="#FF5555">
	<Word>&amp;c</Word>
</Keywords>
```
Is working like this:
![obraz](https://user-images.githubusercontent.com/77281214/178335284-8d420daa-4865-4d94-aeb9-84405dadc2e5.png)
Why? I want it to be always highlighted.

And...
I have this:
```xaml
<Span color="Command">
	<Begin>command </Begin>
	<End>:</End>
	<RuleSet>
		<!-- nested span for escape sequences -->
		<Span begin="#"/>
	</RuleSet>
</Span>
```
It's working okay in what i want:
![obraz](https://user-images.githubusercontent.com/77281214/178335489-f7b67f84-8e71-4923-a568-a6c30eae58c2.png)
But... "command" is red also in the normal text:
![obraz](https://user-images.githubusercontent.com/77281214/178335585-9d6639df-4895-43e2-b36c-2ae8f3fe2390.png)


And i have a question.

I have colors like this:
![obraz](https://user-images.githubusercontent.com/77281214/178335796-d21341d7-b3cc-4de4-bdd4-3a8de672ac69.png)

How can i make it to look like this?
![obraz](https://user-images.githubusercontent.com/77281214/178336066-03bd44f4-c806-4d43-a43e-39cec4de5b84.png)
I hope you understand.

(Sorry, i don't understand regex etc)

**Comment by NotroDev** [comment]
> This is probably what you want:
> 
> ```
> <?xml version="1.0"?>
> <SyntaxDefinition name="Custom Highlighting" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
> 	<Color name="Comment" foreground="Green" />
> 	<Color name="String" foreground="Blue" />
> 	<Color name="BracedExpression" foreground="Orange" />
> 	
> 	<RuleSet>
> 		<Span color="String" ruleSet="BracedExpressionRuleSet">
> 			<Begin>"</Begin>
> 			<End>"</End>
> 		</Span>
> 
> 		<Import ruleSet="BracedExpressionRuleSet" />
> 	</RuleSet>
> 
> 	<RuleSet name="BracedExpressionRuleSet">
> 		<Span color="BracedExpression">
> 			<Begin>{</Begin>
> 			<End>}</End>
> 		</Span>
> 	</RuleSet>
> </SyntaxDefinition>
> ```

To my last reply.
I can use this code:
```xaml
<Span foreground="#FF5555">
	<Begin>&amp;c</Begin>
	<End>&amp;</End>
</Span>
```
But it colors next & too. I just need to remove it and it will be great...
