### ISSUE TITLE
Make the line to the right of the line numbers have its own color.

### ISSUE THREAD

**Issue by MarioFares** [icsharpcode/AvalonEdit#357]
Currently, one can enable line numbers, which displays the numbers along with a vertical line to the right of those numbers. The color of that dotted line is bound to the foreground of the numbers, which one can set.

However, I think it is better to make the color of that line a separate property. Additionally, I think the option to have the line dotted or solid should be allowed as well.

**Comment by dgrunwald** [comment]
These are only bound together if you use the easy `TextEditor.ShowLineNumbers` property.
All this property does is set up `LineNumberMargin`+`DottedLineMargin` for you: https://github.com/icsharpcode/AvalonEdit/blob/b8d1c28877df89e7d5253d5be7248abbc3e9ffbb/ICSharpCode.AvalonEdit/TextEditor.cs#L478
You can do the same manually to get more control.
