### ISSUE TITLE
Problem with syntax highlighting

### ISSUE THREAD

**Issue by NotroDev** [icsharpcode/AvalonEdit#363]
Hi. I have this syntax highlighting:
https://pastebin.com/4g7EzCPp
There is a problem about `command`.
It's working pretty good normally:
![obraz](https://user-images.githubusercontent.com/77281214/184837476-da056324-f571-4326-b3ac-05f52fb9dd4f.png)
But if there is another highlighting's object, it doesn't override it and doesn't work.
![obraz](https://user-images.githubusercontent.com/77281214/184837657-5f012fc2-4bab-4343-8c3d-ee7953f9e051.png)
And, one more thing. I have this:
```xml
<Span foreground="#41bbe2">
	<Begin>&lt;#</Begin>
	<End>&gt;</End>
</Span>
```
Why the hash doesn't work? Like... Highlighting doesn't care about it.
![obraz](https://user-images.githubusercontent.com/77281214/184837999-491cd4b0-92bb-488f-becb-3fdc7c8a07a0.png)
It should only highlight the second example.

**Comment by siegfriedpammer** [comment]
> Why the hash doesn't work?

regex uses # to denote comments.

**Comment by NotroDev** [comment]
> regex uses # to denote comments.

Ah, okay. Fixed it.

**Comment by NotroDev** [comment]
Oh. The first part works now when i fixed the "<#>". Thanks!

**Comment by NotroDev** [comment]
Oh. No. 
![obraz](https://user-images.githubusercontent.com/77281214/184846625-7cca0fc1-2475-4c58-a4cd-352f34333b3b.png)
So now I just need to override the `""`

**Comment by NotroDev** [comment]
I replaced the regex with this:
```xml
<Span color="Command">
	<Begin>command \u0020/</Begin>
	<End>:</End>
</Span>
```
It works. If I will have any problems,, i'll write.
