### ISSUE TITLE
Is there `this` in AvalonEdit?

### ISSUE THREAD

**Issue by NotroDev** [icsharpcode/AvalonEdit#369]
Hey, is this implemented in AvalonEdit?
![obraz](https://user-images.githubusercontent.com/77281214/186920153-2c03ec74-9e4c-4968-a988-8d1eb4e210b8.png)
If yes, how can I enable it?

**Comment by dgrunwald** [comment]
Visual Studio calls these "structure guide lines".
AvalonEdit does not have this feature.
You could use `IBackgroundRenderer` do add it yourself, but you'd need your own code for detecting (and efficiently updating) the document structure.

**Comment by NotroDev** [comment]
Okay, thanks.
