### ISSUE TITLE
How to change the current line border and background?

### ISSUE THREAD

**Issue by NeuroWhAI** [icsharpcode/AvalonEdit#378]
Hello, I saw there are `CurrentLineBorder` and `CurrentLineBackground` properties to set the highlight style of current line.
But, I couldn't figure out how to access those properties in code.
Does anyone know about this?

**Comment by jimfoye** [comment]
They are TextView properties.

**Comment by NeuroWhAI** [comment]
@jimfoye

Thank you for your reply.
But, I can't find a `TextView` property in the `ICSharpCode.AvalonEdit.TextEditor`.
Please let me know where is it.

**Comment by jimfoye** [comment]
TextView is a property of TextArea. Some good reading:

https://www.codeproject.com/Articles/42490/Using-AvalonEdit-WPF-Text-Editor

**Comment by NeuroWhAI** [comment]
Thank you so much!
