### ISSUE TITLE
Rule Regex doesn't work as expected

### ISSUE THREAD

**Issue by MathiasLui** [icsharpcode/AvalonEdit#392]
Hey, I've got a syntax highlighting rule that should match the first word of each line like this:
`<Rule color="CmdOrVar">
    ^[+\-_a-zA-Z]([\w]*)?(\s|$)
</Rule>`
and it works when trying it on regexr:
![image](https://user-images.githubusercontent.com/29667091/224515473-2cdcfab4-8ab2-43dd-9bfc-7c7ccca0abc3.png)
But in the Editor it looks like this and it feels like it's deciding for each word instead of each line:
![image](https://user-images.githubusercontent.com/29667091/224515503-29bd6bba-ea89-4e8e-b60f-1a24a026bd7a.png)

**Comment by MathiasLui** [comment]
I have tried so long for different solutions for this as well as some other things and it feels impossible to do anything more with regex than just highlighting certain keywords, strings or comments...

Is there maybe a way to write my own logic for highlighting text, based on code instead of regex?

**Comment by jimfoye** [comment]
You can derive a class from DocumentColorizingTransformer.

**Comment by MathiasLui** [comment]
Thanks I'll try that!

**Comment by MathiasLui** [comment]
Thanks, I managed to make that work, uglily, but it works
