### ISSUE TITLE
Rectangle selection does not handle backspace key

### ISSUE THREAD

**Issue by nippur72** [icsharpcode/AvalonEdit#57]
When in rectangle selection, you can type text and have it inserted on each row of the selection; but if you use backspace to edit, the selection cancels and the backspace is applied only the line where the caret is.

Ideally, backspace should be applied on each line of the selection (like in Visual Studio).

**Comment by gwinsky** [comment]
same as https://github.com/icsharpcode/AvalonEdit/issues/22 ?
