### ISSUE TITLE
Control disables when applying Telerik theme to ScrollViewer

### ISSUE THREAD

**Issue by accessguru** [icsharpcode/AvalonEdit#61]
First of all, this is a very cool control.  Great job!  This is an obscure situation, but I notice that the control becomes disabled when I apply the following global style to ScrollViewers.  My project is using Telerik and I'm trying to apply the theme to the project's ScrollViewers.  Once I remove this the control works as expected

```
    <Style TargetType="ScrollViewer">
        <Setter Property="telerik:StyleManager.Theme" Value="{StaticResource Theme}"/>
        <Setter Property="HorizontalScrollBarVisibility" Value="Disabled"/>
        <Setter Property="VerticalScrollBarVisibility" Value="Disabled"/>
    </Style>
```

**Comment by siegfriedpammer** [comment]
Sorry, we have no Telerik license to verify.
