### ISSUE TITLE
Copying empty selection clears clipboard

### ISSUE THREAD

**Issue by avalonedit-user** [icsharpcode/AvalonEdit#62]
When user tries to copy text from TextEditor while the selection is empty, the clipboard is cleared. This is not expected, since most text editors don't behave this way.

Clipboard should not be cleared, when user attempts to do this.

**Comment by dgrunwald** [comment]
The clipboard isn't cleared; it's set to the contents of the current line.
This is the same behavior as Visual Studio.

**Comment by dgrunwald** [comment]
Note that this feature can be disabled by setting `textEditor.Options.CutCopyWholeLine = false;`.
