### ISSUE TITLE
Replacements for AbstractFoldingStrategy and TextMarkerService?

### ISSUE THREAD

**Issue by nadcraker** [icsharpcode/AvalonEdit#71]
I am attempting to update some code that was built on a previous version of AvalonEdit to the latest version, 5.0.1.0.

This older code uses two classes that don't appear to be in the new version. 'AbstractFoldingStrategy' and 'TextMarkerService'. What classes have replaced them?

This is a code sample

``` C#
AbstractFoldingStrategy foldingStrategy;
foldingStrategy = new BraceFoldingStrategy();
foldingStrategy.UpdateFoldings(foldingManager, textEditor.Document);
foldingStrategy.UpdateFoldings(foldingManager, textEditor.Document);
```

``` C#
TextMarkerService textMarkerService;
textMarkerService = new TextMarkerService(this.textEditor.Document);
textEditor.TextArea.TextView.BackgroundRenderers.Add(textMarkerService);
textView.LineTransformers.Add(textMarkerService);
textView.Services.AddService(typeof(ITextMarkerService), textMarkerService);
textMarkerService.RemoveAll();
var m = textMarkerService.Create(startOffset, length);
```

**Comment by VladD2** [comment]
I have the same problem. What can replace AbstractFoldingStrategy?

**Comment by dgrunwald** [comment]
`TextMarkerService` and `AbstractFoldingStrategy` never were part of AvalonEdit. Did you previously use some customized variant of AvalonEdit? Or are you thinking of the win-forms-based `ICSharpCode.TextEditor`?

**Comment by morphx666** [comment]
[Here's the implementation for the AbstractFoldingStrategy class](http://www.symbolsource.org/Public/Metadata/NuGet/Project/AvalonEdit/4.3.0.9390/Release/.NETFramework,Version%3Dv4.0/ICSharpCode.AvalonEdit/ICSharpCode.AvalonEdit/Folding/AbstractFoldingStrategy.cs?ImageName=ICSharpCode.AvalonEdit).

Just add the class to your project and everything should work just fine, regardless of the version of AvalonEdit you're using.

**Comment by christophwille** [comment]
According to https://api.github.com/repos/icsharpcode/avalonedit this repo was created_at 2014-04-10. Version v4.3 (https://www.nuget.org/packages/AvalonEdit/4.3.1.9430) was published still from the SharpDevelop repo. (and here is a current source link https://www.fuget.org/packages/AvalonEdit/4.3.0.9390/lib/net40/ICSharpCode.AvalonEdit.dll/ICSharpCode.AvalonEdit.Folding/AbstractFoldingStrategy)

**Comment by siegfriedpammer** [comment]
The `AbstractFoldingStrategy` class was removed in dbefda9cafdcc20d7ca2a6955943b39411d955a8. There is no direct replacement. You can use the code suggested in https://github.com/icsharpcode/AvalonEdit/issues/71#issuecomment-234396754
