### ISSUE TITLE
Allow more FontWeights

### ISSUE THREAD

**Issue by xxMUROxx** [icsharpcode/AvalonEdit#76]
Is there a possibility to define all the [FontWeights](https://msdn.microsoft.com/en-us/library/system.windows.fontweights(v=vs.110).aspx) that are available in WPF in the [XSD-definition](https://github.com/icsharpcode/AvalonEdit/blob/bb20f682c96ca10dddbdd143a7308fac6626cc07/ICSharpCode.AvalonEdit/Highlighting/Resources/ModeV2.xsd#L13)?

**Comment by dgrunwald** [comment]
I don't see a need for defining all the named values. You can already specify all possible font weights as integer values.
