### ISSUE TITLE
huge memory leaks

### ISSUE THREAD

**Issue by fstarred** [icsharpcode/AvalonEdit#80]
I've noticed that avalonedit take up a lot of memory resources (for 14Mb of content I see more or less 250MB occupied for my application in task manager).

Even when I clear the textarea, memory doesn't clear at all.
Is there any way or trick to clear the ram ?

**Comment by redondogabriel** [comment]
having the same issue, found any fix for this?

**Comment by heldersepu** [comment]
I've been using AvalonEdit for a while now and have not seen any "huge memory leaks" 
Here is my application: 
https://github.com/heldersepu/CodeFetcher

... I don't deal with 14MB files, my files are much smaller, but I do change a lot between files.
I'm curious, What kind of files are you dealing with that are that large?
