### ISSUE TITLE
Add overtype mode

### ISSUE THREAD

**Issue by mike-ward** [icsharpcode/AvalonEdit#85]
I've found editing Markdown tables is easier when there's an overtype mode.

**Comment by dgrunwald** [comment]
That already exists, you just have to enable `textEditor.Options.AllowToggleOverstrikeMode = true;` to allow the user to toggle the mode using the Insert key.

To programmatically get/set the mode, use the `textEditor.TextArea.OverstrikeMode` property.

**Comment by mike-ward** [comment]
Ah, I kept looking for overtype. Silly me... Thanks!
