### ISSUE TITLE
UWP 

### ISSUE THREAD

**Issue by sk8tz** [icsharpcode/AvalonEdit#88]
Before I start even looking at this control, can someone advise if they have this control working/or attempted using this control with an UWP. An what they experience where ? 

Or any response would be appreciated.

**Comment by christophwille** [comment]
On our end (and I simply presume that @dgrunwald didn't either) no.

**Comment by xied75** [comment]
Given wpf is going no where, any chance we can bring this into the new world? Willing to volunteer.

**Comment by SCKelemen** [comment]
@xied75 fork it. I'll help, if we make it MVVM

**Comment by xied75** [comment]
@SCKelemen Done! 
https://github.com/coderobin/AvalonEdit
Let's draft the plan over there then

Best

**Comment by DamianSuess** [comment]
Any word on UWP compliancy?
Sketching out a project to consume this editor and we're trying to outweigh our options of UWP vs traditional desktop, and would like to stick with UWP if possible.

**Comment by christophwille** [comment]
We recently added netcore3.1 support to AvalonEdit, and atm it seems UWP is going nowhere. From our end, UWP support is not planned as stated earlier.
