### ISSUE TITLE
Insert empty VisualLines

### ISSUE THREAD

**Issue by Asser82** [icsharpcode/AvalonEdit#92]
Hello,

we want to use the editor to compare documents side-by-side like it is done in diff tools.

I have to realize empty but editable VisualLines without underlying DocumentLines (ghost lines). The underlying DocumentLines should be generated if the user presses Enter or inserts a character into the ghost lines.

![image](https://cloud.githubusercontent.com/assets/20209403/16802238/144efe22-4900-11e6-9c68-2c7dfd80b8f3.png)

What is the best approach to achieve this?

One way could be to create an intermediate document with empty lines for ghost lines and colorize the background. But the line numbering would be wrong. I really would prefer a solution directly in the view.

Thx

**Comment by arnoldlorincz** [comment]
Hi, did you managed to do this?

**Comment by siegfriedpammer** [comment]
You could take a look at https://github.com/Dirkster99/Aehnlich/ which uses AvalonEdit to implement a Diff-Control.

**Comment by countfnx** [comment]
Hi, i know it's old and closed but I don't want to open another issue regarding the same concern.

I checked the tool **Aehnlich**. Their approach is to insert empty lines and disable the in-built line numbering and display their own custom line numbering but this is not the perfect solution.

Is it already possible to realize this behavior in some other way? Or is it expected that this feature will be built in? That'd be great! ;)
