### ISSUE TITLE
AllowScrollBelowDocument appears to not work in 5.0.3

### ISSUE THREAD

**Issue by mike-ward** [icsharpcode/AvalonEdit#93]
Just noticed that `textEditor.Options.AllowScrollBelowDocument = true` is not working in 5.0.3. I can no longer scroll below the end of the document using the mouse wheel. Using in http://markdownedit.com

**Comment by siegfriedpammer** [comment]
Does this still occur with current versions? I cannot reproduce this.

**Comment by mike-ward** [comment]
Appears to be working in the latest release. Using .NET Core if that matters.
