### ISSUE TITLE
Auto-complete gets confused when auto-word-wrap occurs.

### ISSUE THREAD

**Issue by romandrovich** [icsharpcode/AvalonEdit#95]
Auto-complete gets confused when auto-word-wrap occurs:  Make the first line long enough that the curson is near the end of the text area.  Start typing your new word.  When the word-wrap occurs, the auto-completion window will be closed.

**Comment by ypeuee** [comment]
兄弟，我也不知道你能否看的懂我写的什么，我对你写的代码编辑器很感兴趣，希望能和你联系上。我的email:ypeuee163.com

**Comment by siegfriedpammer** [comment]
Does this still occur with current versions? I cannot reproduce this.
